### ISSUE TITLE
Error in countries/ru.yaml

### ISSUE THREAD

**Issue by dmpichugin** [pariz/countries#1]
Hello. You have errors in **countries/ru.yaml** in 7 and 35 lines.
7 line: official: Русская Федерация -> official: Российская Федерация
35 line: official: Россия Федерация -> official: Российская Федерация

**Comment by pariz** [comment]
Hi! Thanks, please feel free to make a PR to https://github.com/pariz/gountries-creator with the correct translation!

**Comment by dmpichugin** [comment]
Thanks. I did it.
